on: [push]

jobs:
  compile_paper_job:
    runs-on: ubuntu-latest
    name: Compile paper
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get install -qq -y texlive-base texlive-science texlive-xetex texlive-fonts-recommended texlive-latex-extra
        sudo apt-get install lmodern
        wget https://github.com/jgm/pandoc/releases/download/2.11.3.2/pandoc-2.11.3.2-1-amd64.deb
        sudo dpkg -i pandoc-2.11.3.2-1-amd64.deb
    - name: Build guide.html
      run: pandoc guide.md --from=markdown_github-hard_line_breaks+yaml_metadata_block --output=guide.html --css=pandoc.css --standalone --self-contained
    - name: Build vulnerabilities.html
      run: pandoc vulnerabilities.md --from=markdown_github-hard_line_breaks+yaml_metadata_block --output=vulnerabilities.html --css=pandoc.css --standalone --self-contained
    - name: Build guide.pdf
      run: pandoc guide.md --from=markdown_github-hard_line_breaks+yaml_metadata_block --output=guide.pdf -V geometry:margin=1in -V urlcolor:blue
    - name: Build vulnerabilities.pdf
      run: pandoc vulnerabilities.md --from=markdown_github-hard_line_breaks+yaml_metadata_block --output=vulnerabilities.pdf -V geometry:margin=1in -V urlcolor:blue
    - name: Collect results for deployment
      run: |
        mkdir out
        cp *.html out/
        cp *.pdf out/
        cp -R contracts/ out/contracts/
    - name: Deploy materials to gh-pages
      uses: maxheld83/ghpages@68f783a4f5313d776c1599e18479607e71c9c738  # v0.3.0
      env:
        BUILD_DIR: out/
        GH_PAT: ${{ secrets.GH_PAT }}
